version: "2"
checks:
  file-lines:
    config:
      threshold: 250
plugins:
  duplication:
    enabled: true
    exclude_patterns:
      - "src/**/*.test.jsx"
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - node_modules/
  - "**/__tests__/"
